#############################################################################
# Makefile for building: bin/projClustering
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  projClustering.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile projClustering.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -std=c++11 -O2 -D_REENTRANT -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -Isrc/include -I/usr/lib64/qt5/include -I/usr/lib64/qt5/include/QtWidgets -I/usr/lib64/qt5/include/QtGui -I/usr/lib64/qt5/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib64/qt5/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt5
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/gui.cpp moc_gui.cpp
OBJECTS       = main.o \
		gui.o \
		moc_gui.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		projClustering.pro \
		projClustering.pro
QMAKE_TARGET  = projClustering
DESTDIR       = bin/#avoid trailing-slash linebreak
TARGET        = bin/projClustering


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: projClustering.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		projClustering.pro \
		/usr/lib64/qt5/lib/libQt5Widgets.prl \
		/usr/lib64/qt5/lib/libQt5Gui.prl \
		/usr/lib64/qt5/lib/libQt5Core.prl
	$(QMAKE) -o Makefile projClustering.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/shell-unix.conf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
projClustering.pro:
/usr/lib64/qt5/lib/libQt5Widgets.prl:
/usr/lib64/qt5/lib/libQt5Gui.prl:
/usr/lib64/qt5/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile projClustering.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/projClustering1.0.0 || mkdir -p .tmp/projClustering1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/projClustering1.0.0/ && $(COPY_FILE) --parents src/include/gui.hpp .tmp/projClustering1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/gui.cpp .tmp/projClustering1.0.0/ && (cd `dirname .tmp/projClustering1.0.0` && $(TAR) projClustering1.0.0.tar projClustering1.0.0 && $(COMPRESS) projClustering1.0.0.tar) && $(MOVE) `dirname .tmp/projClustering1.0.0`/projClustering1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/projClustering1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/$(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_gui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gui.cpp
moc_gui.cpp: /usr/lib64/qt5/include/QtGui/QtGui \
		/usr/lib64/qt5/include/QtGui/QtGuiDepends \
		/usr/lib64/qt5/include/QtCore/QtCore \
		/usr/lib64/qt5/include/QtCore/QtCoreDepends \
		/usr/lib64/qt5/include/QtCore/qabstractanimation.h \
		/usr/lib64/qt5/include/QtCore/qobject.h \
		/usr/lib64/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib64/qt5/include/QtCore/qnamespace.h \
		/usr/lib64/qt5/include/QtCore/qglobal.h \
		/usr/lib64/qt5/include/QtCore/qconfig.h \
		/usr/lib64/qt5/include/QtCore/qfeatures.h \
		/usr/lib64/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib64/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib64/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib64/qt5/include/QtCore/qglobalstatic.h \
		/usr/lib64/qt5/include/QtCore/qatomic.h \
		/usr/lib64/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib64/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib64/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib64/qt5/include/QtCore/qatomic_power.h \
		/usr/lib64/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib64/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib64/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib64/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib64/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib64/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib64/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib64/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib64/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib64/qt5/include/QtCore/qmutex.h \
		/usr/lib64/qt5/include/QtCore/qlogging.h \
		/usr/lib64/qt5/include/QtCore/qflags.h \
		/usr/lib64/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib64/qt5/include/QtCore/qtypetraits.h \
		/usr/lib64/qt5/include/QtCore/qsysinfo.h \
		/usr/lib64/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib64/qt5/include/QtCore/qstring.h \
		/usr/lib64/qt5/include/QtCore/qchar.h \
		/usr/lib64/qt5/include/QtCore/qbytearray.h \
		/usr/lib64/qt5/include/QtCore/qrefcount.h \
		/usr/lib64/qt5/include/QtCore/qarraydata.h \
		/usr/lib64/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib64/qt5/include/QtCore/qlist.h \
		/usr/lib64/qt5/include/QtCore/qalgorithms.h \
		/usr/lib64/qt5/include/QtCore/qiterator.h \
		/usr/lib64/qt5/include/QtCore/qcoreevent.h \
		/usr/lib64/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib64/qt5/include/QtCore/qmetatype.h \
		/usr/lib64/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib64/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib64/qt5/include/QtCore/qisenum.h \
		/usr/lib64/qt5/include/QtCore/qobject_impl.h \
		/usr/lib64/qt5/include/QtCore/qanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qparallelanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qpauseanimation.h \
		/usr/lib64/qt5/include/QtCore/qpropertyanimation.h \
		/usr/lib64/qt5/include/QtCore/qvariantanimation.h \
		/usr/lib64/qt5/include/QtCore/qeasingcurve.h \
		/usr/lib64/qt5/include/QtCore/qvector.h \
		/usr/lib64/qt5/include/QtCore/qpoint.h \
		/usr/lib64/qt5/include/QtCore/qvariant.h \
		/usr/lib64/qt5/include/QtCore/qmap.h \
		/usr/lib64/qt5/include/QtCore/qpair.h \
		/usr/lib64/qt5/include/QtCore/qdebug.h \
		/usr/lib64/qt5/include/QtCore/qhash.h \
		/usr/lib64/qt5/include/QtCore/qtextstream.h \
		/usr/lib64/qt5/include/QtCore/qiodevice.h \
		/usr/lib64/qt5/include/QtCore/qlocale.h \
		/usr/lib64/qt5/include/QtCore/qshareddata.h \
		/usr/lib64/qt5/include/QtCore/qset.h \
		/usr/lib64/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib64/qt5/include/QtCore/qstringlist.h \
		/usr/lib64/qt5/include/QtCore/qdatastream.h \
		/usr/lib64/qt5/include/QtCore/qregexp.h \
		/usr/lib64/qt5/include/QtCore/qstringmatcher.h \
		/usr/lib64/qt5/include/QtCore/qsequentialanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qtextcodec.h \
		/usr/lib64/qt5/include/QtCore/qendian.h \
		/usr/lib64/qt5/include/QtCore/qlibraryinfo.h \
		/usr/lib64/qt5/include/QtCore/qdatetime.h \
		/usr/lib64/qt5/include/QtCore/qsharedpointer.h \
		/usr/lib64/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/lib64/qt5/include/QtCore/qnumeric.h \
		/usr/lib64/qt5/include/QtCore/qbuffer.h \
		/usr/lib64/qt5/include/QtCore/qdir.h \
		/usr/lib64/qt5/include/QtCore/qfileinfo.h \
		/usr/lib64/qt5/include/QtCore/qfile.h \
		/usr/lib64/qt5/include/QtCore/qfiledevice.h \
		/usr/lib64/qt5/include/QtCore/qdiriterator.h \
		/usr/lib64/qt5/include/QtCore/qfileselector.h \
		/usr/lib64/qt5/include/QtCore/QObject \
		/usr/lib64/qt5/include/QtCore/QStringList \
		/usr/lib64/qt5/include/QtCore/qfilesystemwatcher.h \
		/usr/lib64/qt5/include/QtCore/qlockfile.h \
		/usr/lib64/qt5/include/QtCore/qloggingcategory.h \
		/usr/lib64/qt5/include/QtCore/qprocess.h \
		/usr/lib64/qt5/include/QtCore/qresource.h \
		/usr/lib64/qt5/include/QtCore/qsavefile.h \
		/usr/lib64/qt5/include/QtCore/qsettings.h \
		/usr/lib64/qt5/include/QtCore/qstandardpaths.h \
		/usr/lib64/qt5/include/QtCore/qtemporarydir.h \
		/usr/lib64/qt5/include/QtCore/QScopedPointer \
		/usr/lib64/qt5/include/QtCore/qtemporaryfile.h \
		/usr/lib64/qt5/include/QtCore/qurl.h \
		/usr/lib64/qt5/include/QtCore/qurlquery.h \
		/usr/lib64/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/lib64/qt5/include/QtCore/qabstractproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qidentityproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/lib64/qt5/include/QtCore/qsortfilterproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qstringlistmodel.h \
		/usr/lib64/qt5/include/QtCore/qjsonarray.h \
		/usr/lib64/qt5/include/QtCore/qjsonvalue.h \
		/usr/lib64/qt5/include/QtCore/qjsondocument.h \
		/usr/lib64/qt5/include/QtCore/qjsonobject.h \
		/usr/lib64/qt5/include/QtCore/qabstracteventdispatcher.h \
		/usr/lib64/qt5/include/QtCore/qeventloop.h \
		/usr/lib64/qt5/include/QtCore/qabstractnativeeventfilter.h \
		/usr/lib64/qt5/include/QtCore/qbasictimer.h \
		/usr/lib64/qt5/include/QtCore/qcoreapplication.h \
		/usr/lib64/qt5/include/QtCore/qmath.h \
		/usr/lib64/qt5/include/QtCore/qmetaobject.h \
		/usr/lib64/qt5/include/QtCore/qmimedata.h \
		/usr/lib64/qt5/include/QtCore/qobjectcleanuphandler.h \
		/usr/lib64/qt5/include/QtCore/qpointer.h \
		/usr/lib64/qt5/include/QtCore/qsharedmemory.h \
		/usr/lib64/qt5/include/QtCore/qsignalmapper.h \
		/usr/lib64/qt5/include/QtCore/qsocketnotifier.h \
		/usr/lib64/qt5/include/QtCore/qsystemsemaphore.h \
		/usr/lib64/qt5/include/QtCore/qtimer.h \
		/usr/lib64/qt5/include/QtCore/qtranslator.h \
		/usr/lib64/qt5/include/QtCore/qwineventnotifier.h \
		/usr/lib64/qt5/include/QtCore/qmimedatabase.h \
		/usr/lib64/qt5/include/QtCore/qmimetype.h \
		/usr/lib64/qt5/include/QtCore/qfactoryinterface.h \
		/usr/lib64/qt5/include/QtCore/qlibrary.h \
		/usr/lib64/qt5/include/QtCore/qplugin.h \
		/usr/lib64/qt5/include/QtCore/qpluginloader.h \
		/usr/lib64/qt5/include/QtCore/quuid.h \
		/usr/lib64/qt5/include/QtCore/qabstractstate.h \
		/usr/lib64/qt5/include/QtCore/qabstracttransition.h \
		/usr/lib64/qt5/include/QtCore/qeventtransition.h \
		/usr/lib64/qt5/include/QtCore/qfinalstate.h \
		/usr/lib64/qt5/include/QtCore/qhistorystate.h \
		/usr/lib64/qt5/include/QtCore/qsignaltransition.h \
		/usr/lib64/qt5/include/QtCore/qstate.h \
		/usr/lib64/qt5/include/QtCore/qstatemachine.h \
		/usr/lib64/qt5/include/QtCore/qexception.h \
		/usr/lib64/qt5/include/QtCore/qfuture.h \
		/usr/lib64/qt5/include/QtCore/qfutureinterface.h \
		/usr/lib64/qt5/include/QtCore/qrunnable.h \
		/usr/lib64/qt5/include/QtCore/qresultstore.h \
		/usr/lib64/qt5/include/QtCore/qfuturesynchronizer.h \
		/usr/lib64/qt5/include/QtCore/qfuturewatcher.h \
		/usr/lib64/qt5/include/QtCore/qreadwritelock.h \
		/usr/lib64/qt5/include/QtCore/qsemaphore.h \
		/usr/lib64/qt5/include/QtCore/qthread.h \
		/usr/lib64/qt5/include/QtCore/qthreadpool.h \
		/usr/lib64/qt5/include/QtCore/qthreadstorage.h \
		/usr/lib64/qt5/include/QtCore/qwaitcondition.h \
		/usr/lib64/qt5/include/QtCore/qarraydataops.h \
		/usr/lib64/qt5/include/QtCore/qarraydatapointer.h \
		/usr/lib64/qt5/include/QtCore/qbitarray.h \
		/usr/lib64/qt5/include/QtCore/qbytearraymatcher.h \
		/usr/lib64/qt5/include/QtCore/qcache.h \
		/usr/lib64/qt5/include/QtCore/qcollator.h \
		/usr/lib64/qt5/include/QtCore/qcommandlineoption.h \
		/usr/lib64/qt5/include/QtCore/qcommandlineparser.h \
		/usr/lib64/qt5/include/QtCore/qcryptographichash.h \
		/usr/lib64/qt5/include/QtCore/qelapsedtimer.h \
		/usr/lib64/qt5/include/QtCore/qline.h \
		/usr/lib64/qt5/include/QtCore/qlinkedlist.h \
		/usr/lib64/qt5/include/QtCore/qmargins.h \
		/usr/lib64/qt5/include/QtCore/qrect.h \
		/usr/lib64/qt5/include/QtCore/qsize.h \
		/usr/lib64/qt5/include/QtCore/qmessageauthenticationcode.h \
		/usr/lib64/qt5/include/QtCore/qqueue.h \
		/usr/lib64/qt5/include/QtCore/qregularexpression.h \
		/usr/lib64/qt5/include/QtCore/qscopedvaluerollback.h \
		/usr/lib64/qt5/include/QtCore/qstack.h \
		/usr/lib64/qt5/include/QtCore/qtextboundaryfinder.h \
		/usr/lib64/qt5/include/QtCore/qtimeline.h \
		/usr/lib64/qt5/include/QtCore/qtimezone.h \
		/usr/lib64/qt5/include/QtCore/qxmlstream.h \
		/usr/lib64/qt5/include/QtCore/qtcoreversion.h \
		/usr/lib64/qt5/include/QtGui/qaccessible.h \
		/usr/lib64/qt5/include/QtGui/qcolor.h \
		/usr/lib64/qt5/include/QtGui/qrgb.h \
		/usr/lib64/qt5/include/QtGui/qevent.h \
		/usr/lib64/qt5/include/QtGui/qwindowdefs.h \
		/usr/lib64/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/lib64/qt5/include/QtGui/qregion.h \
		/usr/lib64/qt5/include/QtGui/qkeysequence.h \
		/usr/lib64/qt5/include/QtGui/qvector2d.h \
		/usr/lib64/qt5/include/QtGui/qtouchdevice.h \
		/usr/lib64/qt5/include/QtGui/qaccessiblebridge.h \
		/usr/lib64/qt5/include/QtGui/qaccessibleobject.h \
		/usr/lib64/qt5/include/QtGui/qaccessibleplugin.h \
		/usr/lib64/qt5/include/QtGui/qbitmap.h \
		/usr/lib64/qt5/include/QtGui/qpixmap.h \
		/usr/lib64/qt5/include/QtGui/qpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qimage.h \
		/usr/lib64/qt5/include/QtGui/qtransform.h \
		/usr/lib64/qt5/include/QtGui/qmatrix.h \
		/usr/lib64/qt5/include/QtGui/qpolygon.h \
		/usr/lib64/qt5/include/QtGui/qpainterpath.h \
		/usr/lib64/qt5/include/QtGui/qicon.h \
		/usr/lib64/qt5/include/QtGui/qiconengine.h \
		/usr/lib64/qt5/include/QtGui/qiconengineplugin.h \
		/usr/lib64/qt5/include/QtGui/qimageiohandler.h \
		/usr/lib64/qt5/include/QtGui/qimagereader.h \
		/usr/lib64/qt5/include/QtGui/qimagewriter.h \
		/usr/lib64/qt5/include/QtGui/qmovie.h \
		/usr/lib64/qt5/include/QtGui/qpicture.h \
		/usr/lib64/qt5/include/QtGui/qpictureformatplugin.h \
		/usr/lib64/qt5/include/QtGui/qpixmapcache.h \
		/usr/lib64/qt5/include/QtGui/qstandarditemmodel.h \
		/usr/lib64/qt5/include/QtGui/qbrush.h \
		/usr/lib64/qt5/include/QtGui/qfont.h \
		/usr/lib64/qt5/include/QtGui/qclipboard.h \
		/usr/lib64/qt5/include/QtGui/qcursor.h \
		/usr/lib64/qt5/include/QtGui/qdrag.h \
		/usr/lib64/qt5/include/QtGui/qgenericplugin.h \
		/usr/lib64/qt5/include/QtGui/qgenericpluginfactory.h \
		/usr/lib64/qt5/include/QtGui/qguiapplication.h \
		/usr/lib64/qt5/include/QtGui/qinputmethod.h \
		/usr/lib64/qt5/include/QtGui/qoffscreensurface.h \
		/usr/lib64/qt5/include/QtGui/qsurface.h \
		/usr/lib64/qt5/include/QtGui/qsurfaceformat.h \
		/usr/lib64/qt5/include/QtGui/qopenglcontext.h \
		/usr/lib64/qt5/include/QtGui/QSurfaceFormat \
		/usr/lib64/qt5/include/QtGui/qopengl.h \
		/usr/lib64/qt5/include/QtCore/qt_windows.h \
		/usr/lib64/qt5/include/QtGui/qopengles2ext.h \
		/usr/lib64/qt5/include/QtGui/qopenglext.h \
		/usr/lib64/qt5/include/QtGui/qopenglversionfunctions.h \
		/usr/lib64/qt5/include/QtGui/qpalette.h \
		/usr/lib64/qt5/include/QtGui/qscreen.h \
		/usr/lib64/qt5/include/QtCore/QList \
		/usr/lib64/qt5/include/QtCore/QRect \
		/usr/lib64/qt5/include/QtCore/QSize \
		/usr/lib64/qt5/include/QtCore/QSizeF \
		/usr/lib64/qt5/include/QtGui/QTransform \
		/usr/lib64/qt5/include/QtGui/qsessionmanager.h \
		/usr/lib64/qt5/include/QtGui/qstylehints.h \
		/usr/lib64/qt5/include/QtGui/qwindow.h \
		/usr/lib64/qt5/include/QtCore/QEvent \
		/usr/lib64/qt5/include/QtCore/QMargins \
		/usr/lib64/qt5/include/QtGui/qgenericmatrix.h \
		/usr/lib64/qt5/include/QtGui/qmatrix4x4.h \
		/usr/lib64/qt5/include/QtGui/qvector3d.h \
		/usr/lib64/qt5/include/QtGui/qvector4d.h \
		/usr/lib64/qt5/include/QtGui/qquaternion.h \
		/usr/lib64/qt5/include/QtGui/qopenglbuffer.h \
		/usr/lib64/qt5/include/QtGui/qopengldebug.h \
		/usr/lib64/qt5/include/QtGui/qopenglframebufferobject.h \
		/usr/lib64/qt5/include/QtGui/qopenglfunctions.h \
		/usr/lib64/qt5/include/QtGui/qopenglpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qopenglpixeltransferoptions.h \
		/usr/lib64/qt5/include/QtCore/QSharedDataPointer \
		/usr/lib64/qt5/include/QtGui/qopenglshaderprogram.h \
		/usr/lib64/qt5/include/QtGui/qopengltexture.h \
		/usr/lib64/qt5/include/QtGui/qopengltimerquery.h \
		/usr/lib64/qt5/include/QtGui/qopenglvertexarrayobject.h \
		/usr/lib64/qt5/include/QtGui/qbackingstore.h \
		/usr/lib64/qt5/include/QtGui/qpagedpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qpaintengine.h \
		/usr/lib64/qt5/include/QtGui/qpainter.h \
		/usr/lib64/qt5/include/QtGui/qtextoption.h \
		/usr/lib64/qt5/include/QtGui/qpen.h \
		/usr/lib64/qt5/include/QtGui/qfontinfo.h \
		/usr/lib64/qt5/include/QtGui/qfontmetrics.h \
		/usr/lib64/qt5/include/QtGui/qpdfwriter.h \
		/usr/lib64/qt5/include/QtGui/qabstracttextdocumentlayout.h \
		/usr/lib64/qt5/include/QtGui/qtextlayout.h \
		/usr/lib64/qt5/include/QtGui/qtextformat.h \
		/usr/lib64/qt5/include/QtGui/qglyphrun.h \
		/usr/lib64/qt5/include/QtGui/qrawfont.h \
		/usr/lib64/qt5/include/QtGui/qfontdatabase.h \
		/usr/lib64/qt5/include/QtGui/qtextcursor.h \
		/usr/lib64/qt5/include/QtGui/qtextdocument.h \
		/usr/lib64/qt5/include/QtGui/qstatictext.h \
		/usr/lib64/qt5/include/QtGui/qsyntaxhighlighter.h \
		/usr/lib64/qt5/include/QtGui/qtextobject.h \
		/usr/lib64/qt5/include/QtGui/qtextdocumentfragment.h \
		/usr/lib64/qt5/include/QtGui/qtextdocumentwriter.h \
		/usr/lib64/qt5/include/QtGui/qtextlist.h \
		/usr/lib64/qt5/include/QtGui/qtexttable.h \
		/usr/lib64/qt5/include/QtGui/qdesktopservices.h \
		/usr/lib64/qt5/include/QtGui/qvalidator.h \
		/usr/lib64/qt5/include/QtGui/qtguiversion.h \
		/usr/lib64/qt5/include/QtWidgets/QtWidgets \
		/usr/lib64/qt5/include/QtWidgets/QtWidgetsDepends \
		/usr/lib64/qt5/include/QtWidgets/qaccessiblewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qcolordialog.h \
		/usr/lib64/qt5/include/QtWidgets/qdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/lib64/qt5/include/QtWidgets/qerrormessage.h \
		/usr/lib64/qt5/include/QtWidgets/qfiledialog.h \
		/usr/lib64/qt5/include/QtWidgets/qfilesystemmodel.h \
		/usr/lib64/qt5/include/QtWidgets/qfontdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qinputdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qlineedit.h \
		/usr/lib64/qt5/include/QtWidgets/qframe.h \
		/usr/lib64/qt5/include/QtWidgets/qmessagebox.h \
		/usr/lib64/qt5/include/QtWidgets/qprogressdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qwizard.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicseffect.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsanchorlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslayoutitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsgridlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsitemanimation.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslinearlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsproxywidget.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicswidget.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsscene.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicssceneevent.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicstransform.h \
		/usr/lib64/qt5/include/QtGui/QVector3D \
		/usr/lib64/qt5/include/QtGui/QMatrix4x4 \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsview.h \
		/usr/lib64/qt5/include/QtWidgets/qscrollarea.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleoption.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/lib64/qt5/include/QtWidgets/qslider.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractslider.h \
		/usr/lib64/qt5/include/QtWidgets/qstyle.h \
		/usr/lib64/qt5/include/QtWidgets/qtabbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtabwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qrubberband.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/lib64/qt5/include/QtWidgets/qcolumnview.h \
		/usr/lib64/qt5/include/QtWidgets/qdatawidgetmapper.h \
		/usr/lib64/qt5/include/QtWidgets/qdirmodel.h \
		/usr/lib64/qt5/include/QtWidgets/qfileiconprovider.h \
		/usr/lib64/qt5/include/QtWidgets/qheaderview.h \
		/usr/lib64/qt5/include/QtWidgets/qitemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qitemeditorfactory.h \
		/usr/lib64/qt5/include/QtWidgets/qlistview.h \
		/usr/lib64/qt5/include/QtWidgets/qlistwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleditemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qtableview.h \
		/usr/lib64/qt5/include/QtWidgets/qtablewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qtreeview.h \
		/usr/lib64/qt5/include/QtWidgets/qtreewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qtreewidgetitemiterator.h \
		/usr/lib64/qt5/include/QtWidgets/qaction.h \
		/usr/lib64/qt5/include/QtWidgets/qactiongroup.h \
		/usr/lib64/qt5/include/QtWidgets/qapplication.h \
		/usr/lib64/qt5/include/QtWidgets/qdesktopwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qboxlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgridlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qformlayout.h \
		/usr/lib64/qt5/include/QtWidgets/QLayout \
		/usr/lib64/qt5/include/QtWidgets/qgesture.h \
		/usr/lib64/qt5/include/QtWidgets/qgesturerecognizer.h \
		/usr/lib64/qt5/include/QtWidgets/qshortcut.h \
		/usr/lib64/qt5/include/QtWidgets/qstackedlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qtooltip.h \
		/usr/lib64/qt5/include/QtWidgets/qwhatsthis.h \
		/usr/lib64/qt5/include/QtWidgets/qwidgetaction.h \
		/usr/lib64/qt5/include/QtWidgets/qkeyeventtransition.h \
		/usr/lib64/qt5/include/QtWidgets/qmouseeventtransition.h \
		/usr/lib64/qt5/include/QtWidgets/qcommonstyle.h \
		/usr/lib64/qt5/include/QtWidgets/qdrawutil.h \
		/usr/lib64/qt5/include/QtWidgets/qproxystyle.h \
		/usr/lib64/qt5/include/QtWidgets/QCommonStyle \
		/usr/lib64/qt5/include/QtWidgets/qstylefactory.h \
		/usr/lib64/qt5/include/QtWidgets/qstylepainter.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleplugin.h \
		/usr/lib64/qt5/include/QtWidgets/qcolormap.h \
		/usr/lib64/qt5/include/QtWidgets/qcompleter.h \
		/usr/lib64/qt5/include/QtWidgets/qscroller.h \
		/usr/lib64/qt5/include/QtCore/QPointF \
		/usr/lib64/qt5/include/QtWidgets/QScrollerProperties \
		/usr/lib64/qt5/include/QtWidgets/qscrollerproperties.h \
		/usr/lib64/qt5/include/QtCore/QMetaType \
		/usr/lib64/qt5/include/QtCore/QVariant \
		/usr/lib64/qt5/include/QtWidgets/qsystemtrayicon.h \
		/usr/lib64/qt5/include/QtWidgets/qundogroup.h \
		/usr/lib64/qt5/include/QtWidgets/qundostack.h \
		/usr/lib64/qt5/include/QtWidgets/qundoview.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qbuttongroup.h \
		/usr/lib64/qt5/include/QtWidgets/qcalendarwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qcheckbox.h \
		/usr/lib64/qt5/include/QtWidgets/qcombobox.h \
		/usr/lib64/qt5/include/QtWidgets/qcommandlinkbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qpushbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qdatetimeedit.h \
		/usr/lib64/qt5/include/QtWidgets/qdial.h \
		/usr/lib64/qt5/include/QtWidgets/qdialogbuttonbox.h \
		/usr/lib64/qt5/include/QtWidgets/qdockwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qfocusframe.h \
		/usr/lib64/qt5/include/QtWidgets/qfontcombobox.h \
		/usr/lib64/qt5/include/QtWidgets/qgroupbox.h \
		/usr/lib64/qt5/include/QtWidgets/qkeysequenceedit.h \
		/usr/lib64/qt5/include/QtWidgets/qlabel.h \
		/usr/lib64/qt5/include/QtWidgets/qlcdnumber.h \
		/usr/lib64/qt5/include/QtWidgets/qmainwindow.h \
		/usr/lib64/qt5/include/QtWidgets/qmdiarea.h \
		/usr/lib64/qt5/include/QtWidgets/qmdisubwindow.h \
		/usr/lib64/qt5/include/QtWidgets/qmenu.h \
		/usr/lib64/qt5/include/QtWidgets/qmenubar.h \
		/usr/lib64/qt5/include/QtWidgets/qplaintextedit.h \
		/usr/lib64/qt5/include/QtWidgets/qtextedit.h \
		/usr/lib64/qt5/include/QtWidgets/qprogressbar.h \
		/usr/lib64/qt5/include/QtWidgets/qradiobutton.h \
		/usr/lib64/qt5/include/QtWidgets/qscrollbar.h \
		/usr/lib64/qt5/include/QtWidgets/qsizegrip.h \
		/usr/lib64/qt5/include/QtWidgets/qspinbox.h \
		/usr/lib64/qt5/include/QtWidgets/qsplashscreen.h \
		/usr/lib64/qt5/include/QtWidgets/qsplitter.h \
		/usr/lib64/qt5/include/QtWidgets/qstackedwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qstatusbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtextbrowser.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbox.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qtwidgetsversion.h \
		src/include/gui.hpp
	/usr/lib64/qt5/bin/moc $(DEFINES) $(INCPATH) -I/usr/lib64/gcc/include/c++/4.8.2 -I/usr/lib64/gcc/include/c++/4.8.2/x86_64-slackware-linux -I/usr/lib64/gcc/include/c++/4.8.2/backward -I/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-slackware-linux/4.8.2/include-fixed -I/usr/include src/include/gui.hpp -o moc_gui.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/include/gui.hpp \
		/usr/lib64/qt5/include/QtGui/QtGui \
		/usr/lib64/qt5/include/QtGui/QtGuiDepends \
		/usr/lib64/qt5/include/QtCore/QtCore \
		/usr/lib64/qt5/include/QtCore/QtCoreDepends \
		/usr/lib64/qt5/include/QtCore/qabstractanimation.h \
		/usr/lib64/qt5/include/QtCore/qobject.h \
		/usr/lib64/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib64/qt5/include/QtCore/qnamespace.h \
		/usr/lib64/qt5/include/QtCore/qglobal.h \
		/usr/lib64/qt5/include/QtCore/qconfig.h \
		/usr/lib64/qt5/include/QtCore/qfeatures.h \
		/usr/lib64/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib64/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib64/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib64/qt5/include/QtCore/qglobalstatic.h \
		/usr/lib64/qt5/include/QtCore/qatomic.h \
		/usr/lib64/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib64/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib64/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib64/qt5/include/QtCore/qatomic_power.h \
		/usr/lib64/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib64/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib64/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib64/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib64/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib64/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib64/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib64/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib64/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib64/qt5/include/QtCore/qmutex.h \
		/usr/lib64/qt5/include/QtCore/qlogging.h \
		/usr/lib64/qt5/include/QtCore/qflags.h \
		/usr/lib64/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib64/qt5/include/QtCore/qtypetraits.h \
		/usr/lib64/qt5/include/QtCore/qsysinfo.h \
		/usr/lib64/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib64/qt5/include/QtCore/qstring.h \
		/usr/lib64/qt5/include/QtCore/qchar.h \
		/usr/lib64/qt5/include/QtCore/qbytearray.h \
		/usr/lib64/qt5/include/QtCore/qrefcount.h \
		/usr/lib64/qt5/include/QtCore/qarraydata.h \
		/usr/lib64/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib64/qt5/include/QtCore/qlist.h \
		/usr/lib64/qt5/include/QtCore/qalgorithms.h \
		/usr/lib64/qt5/include/QtCore/qiterator.h \
		/usr/lib64/qt5/include/QtCore/qcoreevent.h \
		/usr/lib64/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib64/qt5/include/QtCore/qmetatype.h \
		/usr/lib64/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib64/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib64/qt5/include/QtCore/qisenum.h \
		/usr/lib64/qt5/include/QtCore/qobject_impl.h \
		/usr/lib64/qt5/include/QtCore/qanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qparallelanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qpauseanimation.h \
		/usr/lib64/qt5/include/QtCore/qpropertyanimation.h \
		/usr/lib64/qt5/include/QtCore/qvariantanimation.h \
		/usr/lib64/qt5/include/QtCore/qeasingcurve.h \
		/usr/lib64/qt5/include/QtCore/qvector.h \
		/usr/lib64/qt5/include/QtCore/qpoint.h \
		/usr/lib64/qt5/include/QtCore/qvariant.h \
		/usr/lib64/qt5/include/QtCore/qmap.h \
		/usr/lib64/qt5/include/QtCore/qpair.h \
		/usr/lib64/qt5/include/QtCore/qdebug.h \
		/usr/lib64/qt5/include/QtCore/qhash.h \
		/usr/lib64/qt5/include/QtCore/qtextstream.h \
		/usr/lib64/qt5/include/QtCore/qiodevice.h \
		/usr/lib64/qt5/include/QtCore/qlocale.h \
		/usr/lib64/qt5/include/QtCore/qshareddata.h \
		/usr/lib64/qt5/include/QtCore/qset.h \
		/usr/lib64/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib64/qt5/include/QtCore/qstringlist.h \
		/usr/lib64/qt5/include/QtCore/qdatastream.h \
		/usr/lib64/qt5/include/QtCore/qregexp.h \
		/usr/lib64/qt5/include/QtCore/qstringmatcher.h \
		/usr/lib64/qt5/include/QtCore/qsequentialanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qtextcodec.h \
		/usr/lib64/qt5/include/QtCore/qendian.h \
		/usr/lib64/qt5/include/QtCore/qlibraryinfo.h \
		/usr/lib64/qt5/include/QtCore/qdatetime.h \
		/usr/lib64/qt5/include/QtCore/qsharedpointer.h \
		/usr/lib64/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/lib64/qt5/include/QtCore/qnumeric.h \
		/usr/lib64/qt5/include/QtCore/qbuffer.h \
		/usr/lib64/qt5/include/QtCore/qdir.h \
		/usr/lib64/qt5/include/QtCore/qfileinfo.h \
		/usr/lib64/qt5/include/QtCore/qfile.h \
		/usr/lib64/qt5/include/QtCore/qfiledevice.h \
		/usr/lib64/qt5/include/QtCore/qdiriterator.h \
		/usr/lib64/qt5/include/QtCore/qfileselector.h \
		/usr/lib64/qt5/include/QtCore/QObject \
		/usr/lib64/qt5/include/QtCore/QStringList \
		/usr/lib64/qt5/include/QtCore/qfilesystemwatcher.h \
		/usr/lib64/qt5/include/QtCore/qlockfile.h \
		/usr/lib64/qt5/include/QtCore/qloggingcategory.h \
		/usr/lib64/qt5/include/QtCore/qprocess.h \
		/usr/lib64/qt5/include/QtCore/qresource.h \
		/usr/lib64/qt5/include/QtCore/qsavefile.h \
		/usr/lib64/qt5/include/QtCore/qsettings.h \
		/usr/lib64/qt5/include/QtCore/qstandardpaths.h \
		/usr/lib64/qt5/include/QtCore/qtemporarydir.h \
		/usr/lib64/qt5/include/QtCore/QScopedPointer \
		/usr/lib64/qt5/include/QtCore/qtemporaryfile.h \
		/usr/lib64/qt5/include/QtCore/qurl.h \
		/usr/lib64/qt5/include/QtCore/qurlquery.h \
		/usr/lib64/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/lib64/qt5/include/QtCore/qabstractproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qidentityproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/lib64/qt5/include/QtCore/qsortfilterproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qstringlistmodel.h \
		/usr/lib64/qt5/include/QtCore/qjsonarray.h \
		/usr/lib64/qt5/include/QtCore/qjsonvalue.h \
		/usr/lib64/qt5/include/QtCore/qjsondocument.h \
		/usr/lib64/qt5/include/QtCore/qjsonobject.h \
		/usr/lib64/qt5/include/QtCore/qabstracteventdispatcher.h \
		/usr/lib64/qt5/include/QtCore/qeventloop.h \
		/usr/lib64/qt5/include/QtCore/qabstractnativeeventfilter.h \
		/usr/lib64/qt5/include/QtCore/qbasictimer.h \
		/usr/lib64/qt5/include/QtCore/qcoreapplication.h \
		/usr/lib64/qt5/include/QtCore/qmath.h \
		/usr/lib64/qt5/include/QtCore/qmetaobject.h \
		/usr/lib64/qt5/include/QtCore/qmimedata.h \
		/usr/lib64/qt5/include/QtCore/qobjectcleanuphandler.h \
		/usr/lib64/qt5/include/QtCore/qpointer.h \
		/usr/lib64/qt5/include/QtCore/qsharedmemory.h \
		/usr/lib64/qt5/include/QtCore/qsignalmapper.h \
		/usr/lib64/qt5/include/QtCore/qsocketnotifier.h \
		/usr/lib64/qt5/include/QtCore/qsystemsemaphore.h \
		/usr/lib64/qt5/include/QtCore/qtimer.h \
		/usr/lib64/qt5/include/QtCore/qtranslator.h \
		/usr/lib64/qt5/include/QtCore/qwineventnotifier.h \
		/usr/lib64/qt5/include/QtCore/qmimedatabase.h \
		/usr/lib64/qt5/include/QtCore/qmimetype.h \
		/usr/lib64/qt5/include/QtCore/qfactoryinterface.h \
		/usr/lib64/qt5/include/QtCore/qlibrary.h \
		/usr/lib64/qt5/include/QtCore/qplugin.h \
		/usr/lib64/qt5/include/QtCore/qpluginloader.h \
		/usr/lib64/qt5/include/QtCore/quuid.h \
		/usr/lib64/qt5/include/QtCore/qabstractstate.h \
		/usr/lib64/qt5/include/QtCore/qabstracttransition.h \
		/usr/lib64/qt5/include/QtCore/qeventtransition.h \
		/usr/lib64/qt5/include/QtCore/qfinalstate.h \
		/usr/lib64/qt5/include/QtCore/qhistorystate.h \
		/usr/lib64/qt5/include/QtCore/qsignaltransition.h \
		/usr/lib64/qt5/include/QtCore/qstate.h \
		/usr/lib64/qt5/include/QtCore/qstatemachine.h \
		/usr/lib64/qt5/include/QtCore/qexception.h \
		/usr/lib64/qt5/include/QtCore/qfuture.h \
		/usr/lib64/qt5/include/QtCore/qfutureinterface.h \
		/usr/lib64/qt5/include/QtCore/qrunnable.h \
		/usr/lib64/qt5/include/QtCore/qresultstore.h \
		/usr/lib64/qt5/include/QtCore/qfuturesynchronizer.h \
		/usr/lib64/qt5/include/QtCore/qfuturewatcher.h \
		/usr/lib64/qt5/include/QtCore/qreadwritelock.h \
		/usr/lib64/qt5/include/QtCore/qsemaphore.h \
		/usr/lib64/qt5/include/QtCore/qthread.h \
		/usr/lib64/qt5/include/QtCore/qthreadpool.h \
		/usr/lib64/qt5/include/QtCore/qthreadstorage.h \
		/usr/lib64/qt5/include/QtCore/qwaitcondition.h \
		/usr/lib64/qt5/include/QtCore/qarraydataops.h \
		/usr/lib64/qt5/include/QtCore/qarraydatapointer.h \
		/usr/lib64/qt5/include/QtCore/qbitarray.h \
		/usr/lib64/qt5/include/QtCore/qbytearraymatcher.h \
		/usr/lib64/qt5/include/QtCore/qcache.h \
		/usr/lib64/qt5/include/QtCore/qcollator.h \
		/usr/lib64/qt5/include/QtCore/qcommandlineoption.h \
		/usr/lib64/qt5/include/QtCore/qcommandlineparser.h \
		/usr/lib64/qt5/include/QtCore/qcryptographichash.h \
		/usr/lib64/qt5/include/QtCore/qelapsedtimer.h \
		/usr/lib64/qt5/include/QtCore/qline.h \
		/usr/lib64/qt5/include/QtCore/qlinkedlist.h \
		/usr/lib64/qt5/include/QtCore/qmargins.h \
		/usr/lib64/qt5/include/QtCore/qrect.h \
		/usr/lib64/qt5/include/QtCore/qsize.h \
		/usr/lib64/qt5/include/QtCore/qmessageauthenticationcode.h \
		/usr/lib64/qt5/include/QtCore/qqueue.h \
		/usr/lib64/qt5/include/QtCore/qregularexpression.h \
		/usr/lib64/qt5/include/QtCore/qscopedvaluerollback.h \
		/usr/lib64/qt5/include/QtCore/qstack.h \
		/usr/lib64/qt5/include/QtCore/qtextboundaryfinder.h \
		/usr/lib64/qt5/include/QtCore/qtimeline.h \
		/usr/lib64/qt5/include/QtCore/qtimezone.h \
		/usr/lib64/qt5/include/QtCore/qxmlstream.h \
		/usr/lib64/qt5/include/QtCore/qtcoreversion.h \
		/usr/lib64/qt5/include/QtGui/qaccessible.h \
		/usr/lib64/qt5/include/QtGui/qcolor.h \
		/usr/lib64/qt5/include/QtGui/qrgb.h \
		/usr/lib64/qt5/include/QtGui/qevent.h \
		/usr/lib64/qt5/include/QtGui/qwindowdefs.h \
		/usr/lib64/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/lib64/qt5/include/QtGui/qregion.h \
		/usr/lib64/qt5/include/QtGui/qkeysequence.h \
		/usr/lib64/qt5/include/QtGui/qvector2d.h \
		/usr/lib64/qt5/include/QtGui/qtouchdevice.h \
		/usr/lib64/qt5/include/QtGui/qaccessiblebridge.h \
		/usr/lib64/qt5/include/QtGui/qaccessibleobject.h \
		/usr/lib64/qt5/include/QtGui/qaccessibleplugin.h \
		/usr/lib64/qt5/include/QtGui/qbitmap.h \
		/usr/lib64/qt5/include/QtGui/qpixmap.h \
		/usr/lib64/qt5/include/QtGui/qpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qimage.h \
		/usr/lib64/qt5/include/QtGui/qtransform.h \
		/usr/lib64/qt5/include/QtGui/qmatrix.h \
		/usr/lib64/qt5/include/QtGui/qpolygon.h \
		/usr/lib64/qt5/include/QtGui/qpainterpath.h \
		/usr/lib64/qt5/include/QtGui/qicon.h \
		/usr/lib64/qt5/include/QtGui/qiconengine.h \
		/usr/lib64/qt5/include/QtGui/qiconengineplugin.h \
		/usr/lib64/qt5/include/QtGui/qimageiohandler.h \
		/usr/lib64/qt5/include/QtGui/qimagereader.h \
		/usr/lib64/qt5/include/QtGui/qimagewriter.h \
		/usr/lib64/qt5/include/QtGui/qmovie.h \
		/usr/lib64/qt5/include/QtGui/qpicture.h \
		/usr/lib64/qt5/include/QtGui/qpictureformatplugin.h \
		/usr/lib64/qt5/include/QtGui/qpixmapcache.h \
		/usr/lib64/qt5/include/QtGui/qstandarditemmodel.h \
		/usr/lib64/qt5/include/QtGui/qbrush.h \
		/usr/lib64/qt5/include/QtGui/qfont.h \
		/usr/lib64/qt5/include/QtGui/qclipboard.h \
		/usr/lib64/qt5/include/QtGui/qcursor.h \
		/usr/lib64/qt5/include/QtGui/qdrag.h \
		/usr/lib64/qt5/include/QtGui/qgenericplugin.h \
		/usr/lib64/qt5/include/QtGui/qgenericpluginfactory.h \
		/usr/lib64/qt5/include/QtGui/qguiapplication.h \
		/usr/lib64/qt5/include/QtGui/qinputmethod.h \
		/usr/lib64/qt5/include/QtGui/qoffscreensurface.h \
		/usr/lib64/qt5/include/QtGui/qsurface.h \
		/usr/lib64/qt5/include/QtGui/qsurfaceformat.h \
		/usr/lib64/qt5/include/QtGui/qopenglcontext.h \
		/usr/lib64/qt5/include/QtGui/QSurfaceFormat \
		/usr/lib64/qt5/include/QtGui/qopengl.h \
		/usr/lib64/qt5/include/QtCore/qt_windows.h \
		/usr/lib64/qt5/include/QtGui/qopengles2ext.h \
		/usr/lib64/qt5/include/QtGui/qopenglext.h \
		/usr/lib64/qt5/include/QtGui/qopenglversionfunctions.h \
		/usr/lib64/qt5/include/QtGui/qpalette.h \
		/usr/lib64/qt5/include/QtGui/qscreen.h \
		/usr/lib64/qt5/include/QtCore/QList \
		/usr/lib64/qt5/include/QtCore/QRect \
		/usr/lib64/qt5/include/QtCore/QSize \
		/usr/lib64/qt5/include/QtCore/QSizeF \
		/usr/lib64/qt5/include/QtGui/QTransform \
		/usr/lib64/qt5/include/QtGui/qsessionmanager.h \
		/usr/lib64/qt5/include/QtGui/qstylehints.h \
		/usr/lib64/qt5/include/QtGui/qwindow.h \
		/usr/lib64/qt5/include/QtCore/QEvent \
		/usr/lib64/qt5/include/QtCore/QMargins \
		/usr/lib64/qt5/include/QtGui/qgenericmatrix.h \
		/usr/lib64/qt5/include/QtGui/qmatrix4x4.h \
		/usr/lib64/qt5/include/QtGui/qvector3d.h \
		/usr/lib64/qt5/include/QtGui/qvector4d.h \
		/usr/lib64/qt5/include/QtGui/qquaternion.h \
		/usr/lib64/qt5/include/QtGui/qopenglbuffer.h \
		/usr/lib64/qt5/include/QtGui/qopengldebug.h \
		/usr/lib64/qt5/include/QtGui/qopenglframebufferobject.h \
		/usr/lib64/qt5/include/QtGui/qopenglfunctions.h \
		/usr/lib64/qt5/include/QtGui/qopenglpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qopenglpixeltransferoptions.h \
		/usr/lib64/qt5/include/QtCore/QSharedDataPointer \
		/usr/lib64/qt5/include/QtGui/qopenglshaderprogram.h \
		/usr/lib64/qt5/include/QtGui/qopengltexture.h \
		/usr/lib64/qt5/include/QtGui/qopengltimerquery.h \
		/usr/lib64/qt5/include/QtGui/qopenglvertexarrayobject.h \
		/usr/lib64/qt5/include/QtGui/qbackingstore.h \
		/usr/lib64/qt5/include/QtGui/qpagedpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qpaintengine.h \
		/usr/lib64/qt5/include/QtGui/qpainter.h \
		/usr/lib64/qt5/include/QtGui/qtextoption.h \
		/usr/lib64/qt5/include/QtGui/qpen.h \
		/usr/lib64/qt5/include/QtGui/qfontinfo.h \
		/usr/lib64/qt5/include/QtGui/qfontmetrics.h \
		/usr/lib64/qt5/include/QtGui/qpdfwriter.h \
		/usr/lib64/qt5/include/QtGui/qabstracttextdocumentlayout.h \
		/usr/lib64/qt5/include/QtGui/qtextlayout.h \
		/usr/lib64/qt5/include/QtGui/qtextformat.h \
		/usr/lib64/qt5/include/QtGui/qglyphrun.h \
		/usr/lib64/qt5/include/QtGui/qrawfont.h \
		/usr/lib64/qt5/include/QtGui/qfontdatabase.h \
		/usr/lib64/qt5/include/QtGui/qtextcursor.h \
		/usr/lib64/qt5/include/QtGui/qtextdocument.h \
		/usr/lib64/qt5/include/QtGui/qstatictext.h \
		/usr/lib64/qt5/include/QtGui/qsyntaxhighlighter.h \
		/usr/lib64/qt5/include/QtGui/qtextobject.h \
		/usr/lib64/qt5/include/QtGui/qtextdocumentfragment.h \
		/usr/lib64/qt5/include/QtGui/qtextdocumentwriter.h \
		/usr/lib64/qt5/include/QtGui/qtextlist.h \
		/usr/lib64/qt5/include/QtGui/qtexttable.h \
		/usr/lib64/qt5/include/QtGui/qdesktopservices.h \
		/usr/lib64/qt5/include/QtGui/qvalidator.h \
		/usr/lib64/qt5/include/QtGui/qtguiversion.h \
		/usr/lib64/qt5/include/QtWidgets/QtWidgets \
		/usr/lib64/qt5/include/QtWidgets/QtWidgetsDepends \
		/usr/lib64/qt5/include/QtWidgets/qaccessiblewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qcolordialog.h \
		/usr/lib64/qt5/include/QtWidgets/qdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/lib64/qt5/include/QtWidgets/qerrormessage.h \
		/usr/lib64/qt5/include/QtWidgets/qfiledialog.h \
		/usr/lib64/qt5/include/QtWidgets/qfilesystemmodel.h \
		/usr/lib64/qt5/include/QtWidgets/qfontdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qinputdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qlineedit.h \
		/usr/lib64/qt5/include/QtWidgets/qframe.h \
		/usr/lib64/qt5/include/QtWidgets/qmessagebox.h \
		/usr/lib64/qt5/include/QtWidgets/qprogressdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qwizard.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicseffect.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsanchorlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslayoutitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsgridlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsitemanimation.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslinearlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsproxywidget.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicswidget.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsscene.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicssceneevent.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicstransform.h \
		/usr/lib64/qt5/include/QtGui/QVector3D \
		/usr/lib64/qt5/include/QtGui/QMatrix4x4 \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsview.h \
		/usr/lib64/qt5/include/QtWidgets/qscrollarea.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleoption.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/lib64/qt5/include/QtWidgets/qslider.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractslider.h \
		/usr/lib64/qt5/include/QtWidgets/qstyle.h \
		/usr/lib64/qt5/include/QtWidgets/qtabbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtabwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qrubberband.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/lib64/qt5/include/QtWidgets/qcolumnview.h \
		/usr/lib64/qt5/include/QtWidgets/qdatawidgetmapper.h \
		/usr/lib64/qt5/include/QtWidgets/qdirmodel.h \
		/usr/lib64/qt5/include/QtWidgets/qfileiconprovider.h \
		/usr/lib64/qt5/include/QtWidgets/qheaderview.h \
		/usr/lib64/qt5/include/QtWidgets/qitemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qitemeditorfactory.h \
		/usr/lib64/qt5/include/QtWidgets/qlistview.h \
		/usr/lib64/qt5/include/QtWidgets/qlistwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleditemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qtableview.h \
		/usr/lib64/qt5/include/QtWidgets/qtablewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qtreeview.h \
		/usr/lib64/qt5/include/QtWidgets/qtreewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qtreewidgetitemiterator.h \
		/usr/lib64/qt5/include/QtWidgets/qaction.h \
		/usr/lib64/qt5/include/QtWidgets/qactiongroup.h \
		/usr/lib64/qt5/include/QtWidgets/qapplication.h \
		/usr/lib64/qt5/include/QtWidgets/qdesktopwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qboxlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgridlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qformlayout.h \
		/usr/lib64/qt5/include/QtWidgets/QLayout \
		/usr/lib64/qt5/include/QtWidgets/qgesture.h \
		/usr/lib64/qt5/include/QtWidgets/qgesturerecognizer.h \
		/usr/lib64/qt5/include/QtWidgets/qshortcut.h \
		/usr/lib64/qt5/include/QtWidgets/qstackedlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qtooltip.h \
		/usr/lib64/qt5/include/QtWidgets/qwhatsthis.h \
		/usr/lib64/qt5/include/QtWidgets/qwidgetaction.h \
		/usr/lib64/qt5/include/QtWidgets/qkeyeventtransition.h \
		/usr/lib64/qt5/include/QtWidgets/qmouseeventtransition.h \
		/usr/lib64/qt5/include/QtWidgets/qcommonstyle.h \
		/usr/lib64/qt5/include/QtWidgets/qdrawutil.h \
		/usr/lib64/qt5/include/QtWidgets/qproxystyle.h \
		/usr/lib64/qt5/include/QtWidgets/QCommonStyle \
		/usr/lib64/qt5/include/QtWidgets/qstylefactory.h \
		/usr/lib64/qt5/include/QtWidgets/qstylepainter.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleplugin.h \
		/usr/lib64/qt5/include/QtWidgets/qcolormap.h \
		/usr/lib64/qt5/include/QtWidgets/qcompleter.h \
		/usr/lib64/qt5/include/QtWidgets/qscroller.h \
		/usr/lib64/qt5/include/QtCore/QPointF \
		/usr/lib64/qt5/include/QtWidgets/QScrollerProperties \
		/usr/lib64/qt5/include/QtWidgets/qscrollerproperties.h \
		/usr/lib64/qt5/include/QtCore/QMetaType \
		/usr/lib64/qt5/include/QtCore/QVariant \
		/usr/lib64/qt5/include/QtWidgets/qsystemtrayicon.h \
		/usr/lib64/qt5/include/QtWidgets/qundogroup.h \
		/usr/lib64/qt5/include/QtWidgets/qundostack.h \
		/usr/lib64/qt5/include/QtWidgets/qundoview.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qbuttongroup.h \
		/usr/lib64/qt5/include/QtWidgets/qcalendarwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qcheckbox.h \
		/usr/lib64/qt5/include/QtWidgets/qcombobox.h \
		/usr/lib64/qt5/include/QtWidgets/qcommandlinkbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qpushbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qdatetimeedit.h \
		/usr/lib64/qt5/include/QtWidgets/qdial.h \
		/usr/lib64/qt5/include/QtWidgets/qdialogbuttonbox.h \
		/usr/lib64/qt5/include/QtWidgets/qdockwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qfocusframe.h \
		/usr/lib64/qt5/include/QtWidgets/qfontcombobox.h \
		/usr/lib64/qt5/include/QtWidgets/qgroupbox.h \
		/usr/lib64/qt5/include/QtWidgets/qkeysequenceedit.h \
		/usr/lib64/qt5/include/QtWidgets/qlabel.h \
		/usr/lib64/qt5/include/QtWidgets/qlcdnumber.h \
		/usr/lib64/qt5/include/QtWidgets/qmainwindow.h \
		/usr/lib64/qt5/include/QtWidgets/qmdiarea.h \
		/usr/lib64/qt5/include/QtWidgets/qmdisubwindow.h \
		/usr/lib64/qt5/include/QtWidgets/qmenu.h \
		/usr/lib64/qt5/include/QtWidgets/qmenubar.h \
		/usr/lib64/qt5/include/QtWidgets/qplaintextedit.h \
		/usr/lib64/qt5/include/QtWidgets/qtextedit.h \
		/usr/lib64/qt5/include/QtWidgets/qprogressbar.h \
		/usr/lib64/qt5/include/QtWidgets/qradiobutton.h \
		/usr/lib64/qt5/include/QtWidgets/qscrollbar.h \
		/usr/lib64/qt5/include/QtWidgets/qsizegrip.h \
		/usr/lib64/qt5/include/QtWidgets/qspinbox.h \
		/usr/lib64/qt5/include/QtWidgets/qsplashscreen.h \
		/usr/lib64/qt5/include/QtWidgets/qsplitter.h \
		/usr/lib64/qt5/include/QtWidgets/qstackedwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qstatusbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtextbrowser.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbox.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

gui.o: src/gui.cpp src/include/gui.hpp \
		/usr/lib64/qt5/include/QtGui/QtGui \
		/usr/lib64/qt5/include/QtGui/QtGuiDepends \
		/usr/lib64/qt5/include/QtCore/QtCore \
		/usr/lib64/qt5/include/QtCore/QtCoreDepends \
		/usr/lib64/qt5/include/QtCore/qabstractanimation.h \
		/usr/lib64/qt5/include/QtCore/qobject.h \
		/usr/lib64/qt5/include/QtCore/qobjectdefs.h \
		/usr/lib64/qt5/include/QtCore/qnamespace.h \
		/usr/lib64/qt5/include/QtCore/qglobal.h \
		/usr/lib64/qt5/include/QtCore/qconfig.h \
		/usr/lib64/qt5/include/QtCore/qfeatures.h \
		/usr/lib64/qt5/include/QtCore/qsystemdetection.h \
		/usr/lib64/qt5/include/QtCore/qprocessordetection.h \
		/usr/lib64/qt5/include/QtCore/qcompilerdetection.h \
		/usr/lib64/qt5/include/QtCore/qglobalstatic.h \
		/usr/lib64/qt5/include/QtCore/qatomic.h \
		/usr/lib64/qt5/include/QtCore/qbasicatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/lib64/qt5/include/QtCore/qgenericatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_msvc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_integrity.h \
		/usr/lib64/qt5/include/QtCore/qoldbasicatomic.h \
		/usr/lib64/qt5/include/QtCore/qatomic_vxworks.h \
		/usr/lib64/qt5/include/QtCore/qatomic_power.h \
		/usr/lib64/qt5/include/QtCore/qatomic_alpha.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv7.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv6.h \
		/usr/lib64/qt5/include/QtCore/qatomic_armv5.h \
		/usr/lib64/qt5/include/QtCore/qatomic_bfin.h \
		/usr/lib64/qt5/include/QtCore/qatomic_ia64.h \
		/usr/lib64/qt5/include/QtCore/qatomic_mips.h \
		/usr/lib64/qt5/include/QtCore/qatomic_s390.h \
		/usr/lib64/qt5/include/QtCore/qatomic_sh4a.h \
		/usr/lib64/qt5/include/QtCore/qatomic_sparc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_x86.h \
		/usr/lib64/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/lib64/qt5/include/QtCore/qatomic_gcc.h \
		/usr/lib64/qt5/include/QtCore/qatomic_unix.h \
		/usr/lib64/qt5/include/QtCore/qmutex.h \
		/usr/lib64/qt5/include/QtCore/qlogging.h \
		/usr/lib64/qt5/include/QtCore/qflags.h \
		/usr/lib64/qt5/include/QtCore/qtypeinfo.h \
		/usr/lib64/qt5/include/QtCore/qtypetraits.h \
		/usr/lib64/qt5/include/QtCore/qsysinfo.h \
		/usr/lib64/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/lib64/qt5/include/QtCore/qstring.h \
		/usr/lib64/qt5/include/QtCore/qchar.h \
		/usr/lib64/qt5/include/QtCore/qbytearray.h \
		/usr/lib64/qt5/include/QtCore/qrefcount.h \
		/usr/lib64/qt5/include/QtCore/qarraydata.h \
		/usr/lib64/qt5/include/QtCore/qstringbuilder.h \
		/usr/lib64/qt5/include/QtCore/qlist.h \
		/usr/lib64/qt5/include/QtCore/qalgorithms.h \
		/usr/lib64/qt5/include/QtCore/qiterator.h \
		/usr/lib64/qt5/include/QtCore/qcoreevent.h \
		/usr/lib64/qt5/include/QtCore/qscopedpointer.h \
		/usr/lib64/qt5/include/QtCore/qmetatype.h \
		/usr/lib64/qt5/include/QtCore/qvarlengtharray.h \
		/usr/lib64/qt5/include/QtCore/qcontainerfwd.h \
		/usr/lib64/qt5/include/QtCore/qisenum.h \
		/usr/lib64/qt5/include/QtCore/qobject_impl.h \
		/usr/lib64/qt5/include/QtCore/qanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qparallelanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qpauseanimation.h \
		/usr/lib64/qt5/include/QtCore/qpropertyanimation.h \
		/usr/lib64/qt5/include/QtCore/qvariantanimation.h \
		/usr/lib64/qt5/include/QtCore/qeasingcurve.h \
		/usr/lib64/qt5/include/QtCore/qvector.h \
		/usr/lib64/qt5/include/QtCore/qpoint.h \
		/usr/lib64/qt5/include/QtCore/qvariant.h \
		/usr/lib64/qt5/include/QtCore/qmap.h \
		/usr/lib64/qt5/include/QtCore/qpair.h \
		/usr/lib64/qt5/include/QtCore/qdebug.h \
		/usr/lib64/qt5/include/QtCore/qhash.h \
		/usr/lib64/qt5/include/QtCore/qtextstream.h \
		/usr/lib64/qt5/include/QtCore/qiodevice.h \
		/usr/lib64/qt5/include/QtCore/qlocale.h \
		/usr/lib64/qt5/include/QtCore/qshareddata.h \
		/usr/lib64/qt5/include/QtCore/qset.h \
		/usr/lib64/qt5/include/QtCore/qcontiguouscache.h \
		/usr/lib64/qt5/include/QtCore/qstringlist.h \
		/usr/lib64/qt5/include/QtCore/qdatastream.h \
		/usr/lib64/qt5/include/QtCore/qregexp.h \
		/usr/lib64/qt5/include/QtCore/qstringmatcher.h \
		/usr/lib64/qt5/include/QtCore/qsequentialanimationgroup.h \
		/usr/lib64/qt5/include/QtCore/qtextcodec.h \
		/usr/lib64/qt5/include/QtCore/qendian.h \
		/usr/lib64/qt5/include/QtCore/qlibraryinfo.h \
		/usr/lib64/qt5/include/QtCore/qdatetime.h \
		/usr/lib64/qt5/include/QtCore/qsharedpointer.h \
		/usr/lib64/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/lib64/qt5/include/QtCore/qnumeric.h \
		/usr/lib64/qt5/include/QtCore/qbuffer.h \
		/usr/lib64/qt5/include/QtCore/qdir.h \
		/usr/lib64/qt5/include/QtCore/qfileinfo.h \
		/usr/lib64/qt5/include/QtCore/qfile.h \
		/usr/lib64/qt5/include/QtCore/qfiledevice.h \
		/usr/lib64/qt5/include/QtCore/qdiriterator.h \
		/usr/lib64/qt5/include/QtCore/qfileselector.h \
		/usr/lib64/qt5/include/QtCore/QObject \
		/usr/lib64/qt5/include/QtCore/QStringList \
		/usr/lib64/qt5/include/QtCore/qfilesystemwatcher.h \
		/usr/lib64/qt5/include/QtCore/qlockfile.h \
		/usr/lib64/qt5/include/QtCore/qloggingcategory.h \
		/usr/lib64/qt5/include/QtCore/qprocess.h \
		/usr/lib64/qt5/include/QtCore/qresource.h \
		/usr/lib64/qt5/include/QtCore/qsavefile.h \
		/usr/lib64/qt5/include/QtCore/qsettings.h \
		/usr/lib64/qt5/include/QtCore/qstandardpaths.h \
		/usr/lib64/qt5/include/QtCore/qtemporarydir.h \
		/usr/lib64/qt5/include/QtCore/QScopedPointer \
		/usr/lib64/qt5/include/QtCore/qtemporaryfile.h \
		/usr/lib64/qt5/include/QtCore/qurl.h \
		/usr/lib64/qt5/include/QtCore/qurlquery.h \
		/usr/lib64/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/lib64/qt5/include/QtCore/qabstractproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qidentityproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/lib64/qt5/include/QtCore/qsortfilterproxymodel.h \
		/usr/lib64/qt5/include/QtCore/qstringlistmodel.h \
		/usr/lib64/qt5/include/QtCore/qjsonarray.h \
		/usr/lib64/qt5/include/QtCore/qjsonvalue.h \
		/usr/lib64/qt5/include/QtCore/qjsondocument.h \
		/usr/lib64/qt5/include/QtCore/qjsonobject.h \
		/usr/lib64/qt5/include/QtCore/qabstracteventdispatcher.h \
		/usr/lib64/qt5/include/QtCore/qeventloop.h \
		/usr/lib64/qt5/include/QtCore/qabstractnativeeventfilter.h \
		/usr/lib64/qt5/include/QtCore/qbasictimer.h \
		/usr/lib64/qt5/include/QtCore/qcoreapplication.h \
		/usr/lib64/qt5/include/QtCore/qmath.h \
		/usr/lib64/qt5/include/QtCore/qmetaobject.h \
		/usr/lib64/qt5/include/QtCore/qmimedata.h \
		/usr/lib64/qt5/include/QtCore/qobjectcleanuphandler.h \
		/usr/lib64/qt5/include/QtCore/qpointer.h \
		/usr/lib64/qt5/include/QtCore/qsharedmemory.h \
		/usr/lib64/qt5/include/QtCore/qsignalmapper.h \
		/usr/lib64/qt5/include/QtCore/qsocketnotifier.h \
		/usr/lib64/qt5/include/QtCore/qsystemsemaphore.h \
		/usr/lib64/qt5/include/QtCore/qtimer.h \
		/usr/lib64/qt5/include/QtCore/qtranslator.h \
		/usr/lib64/qt5/include/QtCore/qwineventnotifier.h \
		/usr/lib64/qt5/include/QtCore/qmimedatabase.h \
		/usr/lib64/qt5/include/QtCore/qmimetype.h \
		/usr/lib64/qt5/include/QtCore/qfactoryinterface.h \
		/usr/lib64/qt5/include/QtCore/qlibrary.h \
		/usr/lib64/qt5/include/QtCore/qplugin.h \
		/usr/lib64/qt5/include/QtCore/qpluginloader.h \
		/usr/lib64/qt5/include/QtCore/quuid.h \
		/usr/lib64/qt5/include/QtCore/qabstractstate.h \
		/usr/lib64/qt5/include/QtCore/qabstracttransition.h \
		/usr/lib64/qt5/include/QtCore/qeventtransition.h \
		/usr/lib64/qt5/include/QtCore/qfinalstate.h \
		/usr/lib64/qt5/include/QtCore/qhistorystate.h \
		/usr/lib64/qt5/include/QtCore/qsignaltransition.h \
		/usr/lib64/qt5/include/QtCore/qstate.h \
		/usr/lib64/qt5/include/QtCore/qstatemachine.h \
		/usr/lib64/qt5/include/QtCore/qexception.h \
		/usr/lib64/qt5/include/QtCore/qfuture.h \
		/usr/lib64/qt5/include/QtCore/qfutureinterface.h \
		/usr/lib64/qt5/include/QtCore/qrunnable.h \
		/usr/lib64/qt5/include/QtCore/qresultstore.h \
		/usr/lib64/qt5/include/QtCore/qfuturesynchronizer.h \
		/usr/lib64/qt5/include/QtCore/qfuturewatcher.h \
		/usr/lib64/qt5/include/QtCore/qreadwritelock.h \
		/usr/lib64/qt5/include/QtCore/qsemaphore.h \
		/usr/lib64/qt5/include/QtCore/qthread.h \
		/usr/lib64/qt5/include/QtCore/qthreadpool.h \
		/usr/lib64/qt5/include/QtCore/qthreadstorage.h \
		/usr/lib64/qt5/include/QtCore/qwaitcondition.h \
		/usr/lib64/qt5/include/QtCore/qarraydataops.h \
		/usr/lib64/qt5/include/QtCore/qarraydatapointer.h \
		/usr/lib64/qt5/include/QtCore/qbitarray.h \
		/usr/lib64/qt5/include/QtCore/qbytearraymatcher.h \
		/usr/lib64/qt5/include/QtCore/qcache.h \
		/usr/lib64/qt5/include/QtCore/qcollator.h \
		/usr/lib64/qt5/include/QtCore/qcommandlineoption.h \
		/usr/lib64/qt5/include/QtCore/qcommandlineparser.h \
		/usr/lib64/qt5/include/QtCore/qcryptographichash.h \
		/usr/lib64/qt5/include/QtCore/qelapsedtimer.h \
		/usr/lib64/qt5/include/QtCore/qline.h \
		/usr/lib64/qt5/include/QtCore/qlinkedlist.h \
		/usr/lib64/qt5/include/QtCore/qmargins.h \
		/usr/lib64/qt5/include/QtCore/qrect.h \
		/usr/lib64/qt5/include/QtCore/qsize.h \
		/usr/lib64/qt5/include/QtCore/qmessageauthenticationcode.h \
		/usr/lib64/qt5/include/QtCore/qqueue.h \
		/usr/lib64/qt5/include/QtCore/qregularexpression.h \
		/usr/lib64/qt5/include/QtCore/qscopedvaluerollback.h \
		/usr/lib64/qt5/include/QtCore/qstack.h \
		/usr/lib64/qt5/include/QtCore/qtextboundaryfinder.h \
		/usr/lib64/qt5/include/QtCore/qtimeline.h \
		/usr/lib64/qt5/include/QtCore/qtimezone.h \
		/usr/lib64/qt5/include/QtCore/qxmlstream.h \
		/usr/lib64/qt5/include/QtCore/qtcoreversion.h \
		/usr/lib64/qt5/include/QtGui/qaccessible.h \
		/usr/lib64/qt5/include/QtGui/qcolor.h \
		/usr/lib64/qt5/include/QtGui/qrgb.h \
		/usr/lib64/qt5/include/QtGui/qevent.h \
		/usr/lib64/qt5/include/QtGui/qwindowdefs.h \
		/usr/lib64/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/lib64/qt5/include/QtGui/qregion.h \
		/usr/lib64/qt5/include/QtGui/qkeysequence.h \
		/usr/lib64/qt5/include/QtGui/qvector2d.h \
		/usr/lib64/qt5/include/QtGui/qtouchdevice.h \
		/usr/lib64/qt5/include/QtGui/qaccessiblebridge.h \
		/usr/lib64/qt5/include/QtGui/qaccessibleobject.h \
		/usr/lib64/qt5/include/QtGui/qaccessibleplugin.h \
		/usr/lib64/qt5/include/QtGui/qbitmap.h \
		/usr/lib64/qt5/include/QtGui/qpixmap.h \
		/usr/lib64/qt5/include/QtGui/qpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qimage.h \
		/usr/lib64/qt5/include/QtGui/qtransform.h \
		/usr/lib64/qt5/include/QtGui/qmatrix.h \
		/usr/lib64/qt5/include/QtGui/qpolygon.h \
		/usr/lib64/qt5/include/QtGui/qpainterpath.h \
		/usr/lib64/qt5/include/QtGui/qicon.h \
		/usr/lib64/qt5/include/QtGui/qiconengine.h \
		/usr/lib64/qt5/include/QtGui/qiconengineplugin.h \
		/usr/lib64/qt5/include/QtGui/qimageiohandler.h \
		/usr/lib64/qt5/include/QtGui/qimagereader.h \
		/usr/lib64/qt5/include/QtGui/qimagewriter.h \
		/usr/lib64/qt5/include/QtGui/qmovie.h \
		/usr/lib64/qt5/include/QtGui/qpicture.h \
		/usr/lib64/qt5/include/QtGui/qpictureformatplugin.h \
		/usr/lib64/qt5/include/QtGui/qpixmapcache.h \
		/usr/lib64/qt5/include/QtGui/qstandarditemmodel.h \
		/usr/lib64/qt5/include/QtGui/qbrush.h \
		/usr/lib64/qt5/include/QtGui/qfont.h \
		/usr/lib64/qt5/include/QtGui/qclipboard.h \
		/usr/lib64/qt5/include/QtGui/qcursor.h \
		/usr/lib64/qt5/include/QtGui/qdrag.h \
		/usr/lib64/qt5/include/QtGui/qgenericplugin.h \
		/usr/lib64/qt5/include/QtGui/qgenericpluginfactory.h \
		/usr/lib64/qt5/include/QtGui/qguiapplication.h \
		/usr/lib64/qt5/include/QtGui/qinputmethod.h \
		/usr/lib64/qt5/include/QtGui/qoffscreensurface.h \
		/usr/lib64/qt5/include/QtGui/qsurface.h \
		/usr/lib64/qt5/include/QtGui/qsurfaceformat.h \
		/usr/lib64/qt5/include/QtGui/qopenglcontext.h \
		/usr/lib64/qt5/include/QtGui/QSurfaceFormat \
		/usr/lib64/qt5/include/QtGui/qopengl.h \
		/usr/lib64/qt5/include/QtCore/qt_windows.h \
		/usr/lib64/qt5/include/QtGui/qopengles2ext.h \
		/usr/lib64/qt5/include/QtGui/qopenglext.h \
		/usr/lib64/qt5/include/QtGui/qopenglversionfunctions.h \
		/usr/lib64/qt5/include/QtGui/qpalette.h \
		/usr/lib64/qt5/include/QtGui/qscreen.h \
		/usr/lib64/qt5/include/QtCore/QList \
		/usr/lib64/qt5/include/QtCore/QRect \
		/usr/lib64/qt5/include/QtCore/QSize \
		/usr/lib64/qt5/include/QtCore/QSizeF \
		/usr/lib64/qt5/include/QtGui/QTransform \
		/usr/lib64/qt5/include/QtGui/qsessionmanager.h \
		/usr/lib64/qt5/include/QtGui/qstylehints.h \
		/usr/lib64/qt5/include/QtGui/qwindow.h \
		/usr/lib64/qt5/include/QtCore/QEvent \
		/usr/lib64/qt5/include/QtCore/QMargins \
		/usr/lib64/qt5/include/QtGui/qgenericmatrix.h \
		/usr/lib64/qt5/include/QtGui/qmatrix4x4.h \
		/usr/lib64/qt5/include/QtGui/qvector3d.h \
		/usr/lib64/qt5/include/QtGui/qvector4d.h \
		/usr/lib64/qt5/include/QtGui/qquaternion.h \
		/usr/lib64/qt5/include/QtGui/qopenglbuffer.h \
		/usr/lib64/qt5/include/QtGui/qopengldebug.h \
		/usr/lib64/qt5/include/QtGui/qopenglframebufferobject.h \
		/usr/lib64/qt5/include/QtGui/qopenglfunctions.h \
		/usr/lib64/qt5/include/QtGui/qopenglpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qopenglpixeltransferoptions.h \
		/usr/lib64/qt5/include/QtCore/QSharedDataPointer \
		/usr/lib64/qt5/include/QtGui/qopenglshaderprogram.h \
		/usr/lib64/qt5/include/QtGui/qopengltexture.h \
		/usr/lib64/qt5/include/QtGui/qopengltimerquery.h \
		/usr/lib64/qt5/include/QtGui/qopenglvertexarrayobject.h \
		/usr/lib64/qt5/include/QtGui/qbackingstore.h \
		/usr/lib64/qt5/include/QtGui/qpagedpaintdevice.h \
		/usr/lib64/qt5/include/QtGui/qpaintengine.h \
		/usr/lib64/qt5/include/QtGui/qpainter.h \
		/usr/lib64/qt5/include/QtGui/qtextoption.h \
		/usr/lib64/qt5/include/QtGui/qpen.h \
		/usr/lib64/qt5/include/QtGui/qfontinfo.h \
		/usr/lib64/qt5/include/QtGui/qfontmetrics.h \
		/usr/lib64/qt5/include/QtGui/qpdfwriter.h \
		/usr/lib64/qt5/include/QtGui/qabstracttextdocumentlayout.h \
		/usr/lib64/qt5/include/QtGui/qtextlayout.h \
		/usr/lib64/qt5/include/QtGui/qtextformat.h \
		/usr/lib64/qt5/include/QtGui/qglyphrun.h \
		/usr/lib64/qt5/include/QtGui/qrawfont.h \
		/usr/lib64/qt5/include/QtGui/qfontdatabase.h \
		/usr/lib64/qt5/include/QtGui/qtextcursor.h \
		/usr/lib64/qt5/include/QtGui/qtextdocument.h \
		/usr/lib64/qt5/include/QtGui/qstatictext.h \
		/usr/lib64/qt5/include/QtGui/qsyntaxhighlighter.h \
		/usr/lib64/qt5/include/QtGui/qtextobject.h \
		/usr/lib64/qt5/include/QtGui/qtextdocumentfragment.h \
		/usr/lib64/qt5/include/QtGui/qtextdocumentwriter.h \
		/usr/lib64/qt5/include/QtGui/qtextlist.h \
		/usr/lib64/qt5/include/QtGui/qtexttable.h \
		/usr/lib64/qt5/include/QtGui/qdesktopservices.h \
		/usr/lib64/qt5/include/QtGui/qvalidator.h \
		/usr/lib64/qt5/include/QtGui/qtguiversion.h \
		/usr/lib64/qt5/include/QtWidgets/QtWidgets \
		/usr/lib64/qt5/include/QtWidgets/QtWidgetsDepends \
		/usr/lib64/qt5/include/QtWidgets/qaccessiblewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qcolordialog.h \
		/usr/lib64/qt5/include/QtWidgets/qdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/lib64/qt5/include/QtWidgets/qerrormessage.h \
		/usr/lib64/qt5/include/QtWidgets/qfiledialog.h \
		/usr/lib64/qt5/include/QtWidgets/qfilesystemmodel.h \
		/usr/lib64/qt5/include/QtWidgets/qfontdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qinputdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qlineedit.h \
		/usr/lib64/qt5/include/QtWidgets/qframe.h \
		/usr/lib64/qt5/include/QtWidgets/qmessagebox.h \
		/usr/lib64/qt5/include/QtWidgets/qprogressdialog.h \
		/usr/lib64/qt5/include/QtWidgets/qwizard.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicseffect.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsanchorlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslayoutitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsgridlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsitemanimation.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicslinearlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsproxywidget.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicswidget.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsscene.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicssceneevent.h \
		/usr/lib64/qt5/include/QtWidgets/qgraphicstransform.h \
		/usr/lib64/qt5/include/QtGui/QVector3D \
		/usr/lib64/qt5/include/QtGui/QMatrix4x4 \
		/usr/lib64/qt5/include/QtWidgets/qgraphicsview.h \
		/usr/lib64/qt5/include/QtWidgets/qscrollarea.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleoption.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/lib64/qt5/include/QtWidgets/qslider.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractslider.h \
		/usr/lib64/qt5/include/QtWidgets/qstyle.h \
		/usr/lib64/qt5/include/QtWidgets/qtabbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtabwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qrubberband.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/lib64/qt5/include/QtWidgets/qcolumnview.h \
		/usr/lib64/qt5/include/QtWidgets/qdatawidgetmapper.h \
		/usr/lib64/qt5/include/QtWidgets/qdirmodel.h \
		/usr/lib64/qt5/include/QtWidgets/qfileiconprovider.h \
		/usr/lib64/qt5/include/QtWidgets/qheaderview.h \
		/usr/lib64/qt5/include/QtWidgets/qitemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qitemeditorfactory.h \
		/usr/lib64/qt5/include/QtWidgets/qlistview.h \
		/usr/lib64/qt5/include/QtWidgets/qlistwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleditemdelegate.h \
		/usr/lib64/qt5/include/QtWidgets/qtableview.h \
		/usr/lib64/qt5/include/QtWidgets/qtablewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qtreeview.h \
		/usr/lib64/qt5/include/QtWidgets/qtreewidget.h \
		/usr/lib64/qt5/include/QtWidgets/qtreewidgetitemiterator.h \
		/usr/lib64/qt5/include/QtWidgets/qaction.h \
		/usr/lib64/qt5/include/QtWidgets/qactiongroup.h \
		/usr/lib64/qt5/include/QtWidgets/qapplication.h \
		/usr/lib64/qt5/include/QtWidgets/qdesktopwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qboxlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/lib64/qt5/include/QtWidgets/qgridlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qformlayout.h \
		/usr/lib64/qt5/include/QtWidgets/QLayout \
		/usr/lib64/qt5/include/QtWidgets/qgesture.h \
		/usr/lib64/qt5/include/QtWidgets/qgesturerecognizer.h \
		/usr/lib64/qt5/include/QtWidgets/qshortcut.h \
		/usr/lib64/qt5/include/QtWidgets/qstackedlayout.h \
		/usr/lib64/qt5/include/QtWidgets/qtooltip.h \
		/usr/lib64/qt5/include/QtWidgets/qwhatsthis.h \
		/usr/lib64/qt5/include/QtWidgets/qwidgetaction.h \
		/usr/lib64/qt5/include/QtWidgets/qkeyeventtransition.h \
		/usr/lib64/qt5/include/QtWidgets/qmouseeventtransition.h \
		/usr/lib64/qt5/include/QtWidgets/qcommonstyle.h \
		/usr/lib64/qt5/include/QtWidgets/qdrawutil.h \
		/usr/lib64/qt5/include/QtWidgets/qproxystyle.h \
		/usr/lib64/qt5/include/QtWidgets/QCommonStyle \
		/usr/lib64/qt5/include/QtWidgets/qstylefactory.h \
		/usr/lib64/qt5/include/QtWidgets/qstylepainter.h \
		/usr/lib64/qt5/include/QtWidgets/qstyleplugin.h \
		/usr/lib64/qt5/include/QtWidgets/qcolormap.h \
		/usr/lib64/qt5/include/QtWidgets/qcompleter.h \
		/usr/lib64/qt5/include/QtWidgets/qscroller.h \
		/usr/lib64/qt5/include/QtCore/QPointF \
		/usr/lib64/qt5/include/QtWidgets/QScrollerProperties \
		/usr/lib64/qt5/include/QtWidgets/qscrollerproperties.h \
		/usr/lib64/qt5/include/QtCore/QMetaType \
		/usr/lib64/qt5/include/QtCore/QVariant \
		/usr/lib64/qt5/include/QtWidgets/qsystemtrayicon.h \
		/usr/lib64/qt5/include/QtWidgets/qundogroup.h \
		/usr/lib64/qt5/include/QtWidgets/qundostack.h \
		/usr/lib64/qt5/include/QtWidgets/qundoview.h \
		/usr/lib64/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qbuttongroup.h \
		/usr/lib64/qt5/include/QtWidgets/qcalendarwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qcheckbox.h \
		/usr/lib64/qt5/include/QtWidgets/qcombobox.h \
		/usr/lib64/qt5/include/QtWidgets/qcommandlinkbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qpushbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qdatetimeedit.h \
		/usr/lib64/qt5/include/QtWidgets/qdial.h \
		/usr/lib64/qt5/include/QtWidgets/qdialogbuttonbox.h \
		/usr/lib64/qt5/include/QtWidgets/qdockwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qfocusframe.h \
		/usr/lib64/qt5/include/QtWidgets/qfontcombobox.h \
		/usr/lib64/qt5/include/QtWidgets/qgroupbox.h \
		/usr/lib64/qt5/include/QtWidgets/qkeysequenceedit.h \
		/usr/lib64/qt5/include/QtWidgets/qlabel.h \
		/usr/lib64/qt5/include/QtWidgets/qlcdnumber.h \
		/usr/lib64/qt5/include/QtWidgets/qmainwindow.h \
		/usr/lib64/qt5/include/QtWidgets/qmdiarea.h \
		/usr/lib64/qt5/include/QtWidgets/qmdisubwindow.h \
		/usr/lib64/qt5/include/QtWidgets/qmenu.h \
		/usr/lib64/qt5/include/QtWidgets/qmenubar.h \
		/usr/lib64/qt5/include/QtWidgets/qplaintextedit.h \
		/usr/lib64/qt5/include/QtWidgets/qtextedit.h \
		/usr/lib64/qt5/include/QtWidgets/qprogressbar.h \
		/usr/lib64/qt5/include/QtWidgets/qradiobutton.h \
		/usr/lib64/qt5/include/QtWidgets/qscrollbar.h \
		/usr/lib64/qt5/include/QtWidgets/qsizegrip.h \
		/usr/lib64/qt5/include/QtWidgets/qspinbox.h \
		/usr/lib64/qt5/include/QtWidgets/qsplashscreen.h \
		/usr/lib64/qt5/include/QtWidgets/qsplitter.h \
		/usr/lib64/qt5/include/QtWidgets/qstackedwidget.h \
		/usr/lib64/qt5/include/QtWidgets/qstatusbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtextbrowser.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbar.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbox.h \
		/usr/lib64/qt5/include/QtWidgets/qtoolbutton.h \
		/usr/lib64/qt5/include/QtWidgets/qtwidgetsversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o src/gui.cpp

moc_gui.o: moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gui.o moc_gui.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

